### ISSUE TITLE
Label shipped firmware

### ISSUE THREAD

**Issue by JohnVeness** [Yoti/psp_pspident#2]
At the moment, the shipped firmware version is shown in square brackets after the current firmware version. Can you make it more clear what this is, e.g. putting "shipped firmware:" in front of it, maybe even putting it on a separate line?

Many thanks for this app :)

**Comment by Yoti** [comment]
Yeah, will do in this way in the next release.

**Comment by JohnVeness** [comment]
Many thanks :)

**Comment by Yoti** [comment]
Done: https://github.com/Yoti/psp_pspident/releases/tag/v2.0
