### ISSUE TITLE
DTP-H1500 Screenshot

### ISSUE THREAD

**Issue by ManoDaSilva** [Yoti/psp_pspident#4]
As request by the software, here's a screenshot of the PSPIdent info on my DTP-H1500. I also have a T1000, do you want me to run it too? 

![20231113_002346](https://github.com/Yoti/psp_pspident/assets/13788521/808f5997-56ee-4c33-9550-e61ceb82e583)

Another question: is the serial number stored in any way in the IDStorage? 

Cheers!

**Comment by Yoti** [comment]
Thanks for screenshot!

Yes, it will be great to test on another one T1000.

There is no SN in the IDS (or only few very first models has it).
