### ISSUE TITLE
RU version crash

### ISSUE THREAD

**Issue by RealePSP** [Yoti/psp_pspident#6]
I made RU version, but it cannot launch. Error code: 80020148
Can you talk to me? why it cannot launch?
Sorry for my bad english. Russian message is in ZIP.
[pspIdent_v2.0 RU.zip](https://github.com/Yoti/psp_pspident/files/14001397/pspIdent_v2.0.RU.zip)

**Comment by Yoti** [comment]
Потому, что бинарники НЕ переводятся в текстовых редакторах. Исходники доступны, компилируй нормально.
