### ISSUE TITLE
PSP Go Colorware Prototype/Dev Units - PSPIdent Dumps

### ISSUE THREAD

**Issue by MyquiH** [Yoti/psp_pspident#7]
![20240128_084719_yellow](https://github.com/Yoti/psp_pspident/assets/40738655/a27a5c63-c7bb-4fe5-a9ee-2d942ab77093)
![20090321_234235_blue](https://github.com/Yoti/psp_pspident/assets/40738655/10e3f958-1da0-453d-8f58-38ea331ef88f)
![20090321_232225_magenta](https://github.com/Yoti/psp_pspident/assets/40738655/7850b603-b8fa-4027-8417-9b5faec26677)

**Comment by Yoti** [comment]
Thanks a lot! Proper detection of this units was just added to the pspIdent.
